/**
 * Reading-order tests using real PDF text items extracted via pdf.js.
 *
 * Each test loads actual TextItems from papers in the papers/ folder,
 * runs them through filterNonBodyItems (keeping PDF stream order), and
 * verifies key ordering constraints that a human reader would expect.
 *
 * Fixture: tests/fixtures/real-pdf-items.json
 *   Generated by extracting pages 1 and 12 from each PDF via pdf.js getTextContent().
 */
import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import {
  filterNonBodyItems,
  isParagraphBreak,
  type ItemEntry,
  type TextItem,
} from '../../src/lib/pdf-text';

// ─── Fixture loading ────────────────────────────────────────────────────────

interface FixtureItem {
  str: string;
  x: number;
  y: number;
  w: number;
  h: number;
  fs: number;
  fn: string;
  eol: boolean;
  idx: number;
}

interface PageFixture {
  pageWidth: number;
  pageHeight: number;
  items: FixtureItem[];
}

interface Fixtures {
  [key: string]: PageFixture | { skip: true; reason: string };
}

let fixtures: Fixtures;

function loadPage(key: string): { entries: ItemEntry[]; width: number; height: number } {
  const page = fixtures[key];
  if (!page || 'skip' in page) throw new Error(`Fixture ${key} is skipped or missing`);
  const entries: ItemEntry[] = page.items.map((fi) => ({
    item: {
      str: fi.str,
      dir: 'ltr' as const,
      transform: [1, 0, 0, fi.fs, fi.x, fi.y] as [number, number, number, number, number, number],
      width: fi.w,
      height: fi.h,
      fontName: fi.fn,
      hasEOL: fi.eol,
    },
    index: fi.idx,
  }));
  return { entries, width: page.pageWidth, height: page.pageHeight };
}

/** Join sorted item strings into a single string for substring matching. */
function joinText(items: ItemEntry[]): string {
  return items.map((e) => e.item.str).join(' ');
}

/** Find the index of the first item whose str contains the probe. */
function findItem(items: ItemEntry[], probe: string): number {
  return items.findIndex((e) => e.item.str.includes(probe));
}

/** Assert item A appears before item B in the sorted list. */
function assertBefore(items: ItemEntry[], probeA: string, probeB: string) {
  const iA = findItem(items, probeA);
  const iB = findItem(items, probeB);
  expect(iA, `"${probeA}" not found`).toBeGreaterThanOrEqual(0);
  expect(iB, `"${probeB}" not found`).toBeGreaterThanOrEqual(0);
  expect(iA, `"${probeA}" (idx=${iA}) should come before "${probeB}" (idx=${iB})`).toBeLessThan(iB);
}

beforeAll(() => {
  const raw = readFileSync(join(__dirname, '../fixtures/real-pdf-items.json'), 'utf-8');
  fixtures = JSON.parse(raw);
});

// ═══════════════════════════════════════════════════════════════════════════════
//  paper.pdf page 1: Two-column IEEE paper (title + abstract + intro)
// ═══════════════════════════════════════════════════════════════════════════════

describe('paper.pdf page 1 (two-column IEEE)', () => {
  let sorted: ItemEntry[];
  let filtered: ItemEntry[];

  beforeAll(() => {
    const { entries, width, height } = loadPage('paper_p1');
    filtered = filterNonBodyItems(entries, width, height);
    sorted = filtered; // stream order
  });

  it('filters out the page number "1"', () => {
    const text = joinText(filtered);
    // Page number should be filtered; title should remain
    expect(findItem(filtered, 'A Careful Examination')).toBeGreaterThanOrEqual(0);
    // The standalone "1" at top-right corner should be gone
    const pageNum = filtered.find(
      (e) => e.item.str.trim() === '1' && e.item.transform[5] > 700,
    );
    expect(pageNum).toBeUndefined();
  });

  it('title comes before abstract', () => {
    assertBefore(sorted, 'A Careful Examination', 'Abstract');
  });

  it('author comes before abstract', () => {
    assertBefore(sorted, 'TRI LBM Team', 'Abstract');
  });

  it('abstract comes before Introduction', () => {
    assertBefore(sorted, 'Abstract', 'Introduction');
  });

  it('left column abstract completes before right column body', () => {
    // The abstract ends with project page URL; right column starts with "coordination"
    assertBefore(sorted, 'toyotaresearchinstitute', 'coordination');
  });

  it('Introduction body in left column comes before right column continuation', () => {
    // "Achieving flexible" is intro left col; right col text follows after all left col
    assertBefore(sorted, 'Achieving flexible', 'coordination');
  });

  it('does not interleave columns (body text in left column contiguous)', () => {
    // In stream order, left-column body should appear before right-column body.
    // Full-width items (title, authors) may span across the column boundary.
    // We only check that body-sized left-column text doesn't appear AFTER
    // a substantial block of right-column text.
    const rightColStart = 300;
    let rightColCount = 0;
    let failedItem: string | null = null;
    for (const item of sorted) {
      const x = item.item.transform[4];
      const fontSize = Math.abs(item.item.transform[3]);
      // Skip non-body items (zero-size annotations, watermarks, etc.)
      if (fontSize === 0 || fontSize > 12) continue;
      if (item.item.str.trim() === '') continue;
      if (x > rightColStart) {
        rightColCount++;
      } else {
        // After seeing many right-column items, seeing left-column body is wrong
        if (rightColCount > 10) {
          failedItem = item.item.str;
          break;
        }
      }
    }
    expect(failedItem).toBeNull();
  });

  it('reading order produces coherent abstract text', () => {
    const text = joinText(sorted);
    // The abstract should read continuously
    expect(text).toContain('Robot manipulation has seen tremendous');
    expect(text).toContain('current capabilities');
    // The abstract's second paragraph
    expect(text).toContain('we rigorously evaluate multitask robot');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
//  paper.pdf page 12: Two-column with figure + equations
// ═══════════════════════════════════════════════════════════════════════════════

describe('paper.pdf page 12 (two-column, figure + equations)', () => {
  let sorted: ItemEntry[];
  let filtered: ItemEntry[];

  beforeAll(() => {
    const { entries, width, height } = loadPage('paper_p12');
    filtered = filterNonBodyItems(entries, width, height);
    sorted = filtered; // stream order
  });

  it('filters out the page number "12"', () => {
    const pageNum = filtered.find(
      (e) => e.item.str.trim() === '12' && e.item.transform[5] > 700,
    );
    expect(pageNum).toBeUndefined();
  });

  it('figure caption comes before body text', () => {
    // Figure caption "Figure 9:" is at y=546, body starts at y=493
    assertBefore(sorted, 'Figure 9:', 'Denoising Diffusion');
  });

  it('left column body before right column body', () => {
    // Left column: "Denoising Diffusion Implicit Models"
    // Right column: "To extract features from the image"
    assertBefore(sorted, 'Denoising Diffusion', 'To extract features');
  });

  it('equations appear in correct position within surrounding text', () => {
    // Equation (1) is between text about DDIM update and explanation
    const text = joinText(sorted);
    // The text about modifying DDIM should come before the explanation about noisy actions
    expect(text).toContain('Denoising Diffusion Implicit Models');
  });

  it('subsection headers appear in order', () => {
    // "2) Policy Architecture:" is a subsection in the left column
    // "3) Training and Deployment:" is in the right column
    assertBefore(sorted, 'Policy Architecture', 'Training and Deployment');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
//  arxiv paper page 1: Single-column with sidebar
// ═══════════════════════════════════════════════════════════════════════════════

describe('arxiv paper page 1 (single-column)', () => {
  let sorted: ItemEntry[];
  let filtered: ItemEntry[];

  beforeAll(() => {
    const { entries, width, height } = loadPage('arxiv_p1');
    filtered = filterNonBodyItems(entries, width, height);
    sorted = filtered; // stream order
  });

  it('title comes before authors', () => {
    assertBefore(sorted, 'NeurIPS 2025', 'Mouadh Yagoubi');
  });

  it('authors come before Abstract', () => {
    assertBefore(sorted, 'Mouadh Yagoubi', 'Abstract');
  });

  it('Abstract heading before abstract body', () => {
    assertBefore(sorted, 'Abstract', 'Existing benchmarks');
  });

  it('abstract body before Keywords', () => {
    assertBefore(sorted, 'earliest phases of model development', 'Keywords');
  });

  it('reads generally top-to-bottom', () => {
    // Stream order follows reading order but may include inline elements
    // (superscripts, footnote markers) that break strict Y ordering.
    // Verify the overall trend is top-to-bottom by checking that the
    // median Y movement is downward (Y decreasing in PDF coords).
    const bodyItems = sorted.filter((e) => e.item.transform[4] > 80);
    let downward = 0;
    let upward = 0;
    for (let i = 1; i < bodyItems.length; i++) {
      const yDelta = bodyItems[i - 1].item.transform[5] - bodyItems[i].item.transform[5];
      if (yDelta > 2) downward++;
      else if (yDelta < -2) upward++;
    }
    // Vast majority of transitions should be downward
    expect(downward).toBeGreaterThan(upward * 3);
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
//  arxiv paper page 12: Single-column references → section transition
// ═══════════════════════════════════════════════════════════════════════════════

describe('arxiv paper page 12 (references → section)', () => {
  let sorted: ItemEntry[];
  let filtered: ItemEntry[];

  beforeAll(() => {
    const { entries, width, height } = loadPage('arxiv_p12');
    filtered = filterNonBodyItems(entries, width, height);
    sorted = filtered; // stream order
  });

  it('filters out the centered page number "12"', () => {
    // Page number "12" is at (301, 42) — centered at bottom of page
    const pageNum = filtered.find(
      (e) => e.item.str.trim() === '12' && e.item.transform[5] < 50,
    );
    expect(pageNum).toBeUndefined();
  });

  it('references appear in numerical order', () => {
    assertBefore(sorted, '[44]', '[45]');
    assertBefore(sorted, '[45]', '[46]');
    assertBefore(sorted, '[46]', '[47]');
    assertBefore(sorted, '[48]', '[49]');
  });

  it('references come before section heading "Resources"', () => {
    assertBefore(sorted, '[49]', 'Resources');
  });

  it('section heading before subsection content', () => {
    assertBefore(sorted, 'Resources', 'Organizing team');
  });

  it('author bios appear in order after section intro', () => {
    assertBefore(sorted, 'Organizing team', 'Mouadh Yagoubi');
    assertBefore(sorted, 'Mouadh Yagoubi', 'Yasser Dahou');
    assertBefore(sorted, 'Yasser Dahou', 'Billel Mokeddem');
    assertBefore(sorted, 'Billel Mokeddem', 'Younes Belkada');
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
//  math151 page 1: Table of contents
// ═══════════════════════════════════════════════════════════════════════════════

describe('math151 page 1 (table of contents)', () => {
  let sorted: ItemEntry[];
  let filtered: ItemEntry[];

  beforeAll(() => {
    const { entries, width, height } = loadPage('math151_p1');
    filtered = filterNonBodyItems(entries, width, height);
    sorted = filtered; // stream order
  });

  it('header comes first', () => {
    // "MATH 151" header is at the top
    const text = joinText(sorted);
    const mathIdx = text.indexOf('ATH');
    expect(mathIdx).toBeGreaterThanOrEqual(0);
    expect(mathIdx).toBeLessThan(30); // Should be near the start
  });

  it('Contents heading before section list', () => {
    assertBefore(sorted, 'Contents', 'Probability');
  });

  it('section numbers appear in order', () => {
    // Section headings: 1. Probability, 2. Discrete probabilities, 3. Conditional, 4. Independence, 5. Bayes
    assertBefore(sorted, 'Probability: Definitions', 'Discrete probabilities');
    assertBefore(sorted, 'Discrete probabilities', 'Conditional Probabilities');
    assertBefore(sorted, 'Conditional Probabilities', 'Independence');
    assertBefore(sorted, 'Independence', 'Bayes Theorem');
  });

  it('reads top-to-bottom', () => {
    // All items should decrease in y-coordinate (top of page has higher y)
    for (let i = 1; i < sorted.length; i++) {
      const yPrev = sorted[i - 1].item.transform[5];
      const yCurr = sorted[i].item.transform[5];
      if (yCurr > yPrev + 2) {
        // Same-line items are OK (x-sorted)
        const xPrev = sorted[i - 1].item.transform[4];
        const xCurr = sorted[i].item.transform[4];
        if (xCurr <= xPrev) {
          throw new Error(
            `Out-of-order: "${sorted[i].item.str}" (y=${yCurr}) after "${sorted[i - 1].item.str}" (y=${yPrev})`,
          );
        }
      }
    }
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
//  math151 page 12: Single-column with equations and tables
// ═══════════════════════════════════════════════════════════════════════════════

describe('math151 page 12 (math content with equations/tables)', () => {
  let sorted: ItemEntry[];
  let filtered: ItemEntry[];

  beforeAll(() => {
    const { entries, width, height } = loadPage('math151_p12');
    filtered = filterNonBodyItems(entries, width, height);
    sorted = filtered; // stream order
  });

  it('axiom list comes before probability formula', () => {
    // Axiom text about probability comes before the formula explanation
    assertBefore(sorted, 'Sample Space', 'probability,');
  });

  it('explanation comes before dice example', () => {
    // "COUNTING THINGS" comes after Pr(E) explanation
    assertBefore(sorted, 'COUNTING THINGS', 'Suppose we throw two fair');
  });

  it('section heading "How to count" comes after dice example', () => {
    assertBefore(sorted, 'Suppose we throw two fair', 'How to count');
  });

  it('numbered principles follow section heading', () => {
    assertBefore(sorted, 'How to count', 'multiplication principle');
    assertBefore(sorted, 'multiplication principle', 'Arrangements');
    assertBefore(sorted, 'Arrangements', 'Permutations');
  });

  it('reads generally top-to-bottom (single-column math)', () => {
    // Stream order follows reading order but may include superscripts,
    // subscripts, or equation fragments that break strict Y ordering.
    const mainItems = sorted.filter((e) => e.item.transform[4] > 60);
    let downward = 0;
    let upward = 0;
    for (let i = 1; i < mainItems.length; i++) {
      const yDelta = mainItems[i - 1].item.transform[5] - mainItems[i].item.transform[5];
      if (yDelta > 5) downward++;
      else if (yDelta < -5) upward++;
    }
    expect(downward).toBeGreaterThan(upward * 2);
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
//  docarmo pages: image-only, no text to extract
// ═══════════════════════════════════════════════════════════════════════════════

describe('docarmo (book cover and blank page)', () => {
  it('page 1 (cover) has no extractable text', () => {
    const page = fixtures['docarmo_p1'];
    expect(page).toBeDefined();
    expect('skip' in page!).toBe(true);
  });

  it('page 12 (blank) has no extractable text', () => {
    const page = fixtures['docarmo_p12'];
    expect(page).toBeDefined();
    expect('skip' in page!).toBe(true);
  });
});

// ═══════════════════════════════════════════════════════════════════════════════
//  Cross-paper: sentence splitting on real content
// ═══════════════════════════════════════════════════════════════════════════════

describe('sentence splitting on real extracted text', () => {
  it('paper_p1: reading order produces multiple coherent text chunks', () => {
    const { entries, width, height } = loadPage('paper_p1');
    const filtered = filterNonBodyItems(entries, width, height);
    const sorted = filtered; // stream order

    // Build the full concatenated text as our code would
    const fullText = sorted
      .map((e) => e.item.str)
      .join(' ')
      .replace(/\s+/g, ' ');

    // Should have substantial text
    expect(fullText.length).toBeGreaterThan(500);
    // Title, abstract and intro should all be present
    expect(fullText).toContain('Careful Examination');
    expect(fullText).toContain('Abstract');
    expect(fullText).toContain('Introduction');
    // Multiple sentence-ending periods
    const periodCount = (fullText.match(/\.\s/g) || []).length;
    expect(periodCount).toBeGreaterThan(5);
  });

  it('arxiv_p12: text flows from references to section content', () => {
    const { entries, width, height } = loadPage('arxiv_p12');
    const filtered = filterNonBodyItems(entries, width, height);
    const sorted = filtered; // stream order

    const fullText = sorted
      .map((e) => e.item.str)
      .join(' ')
      .replace(/\s+/g, ' ');

    // References should appear before the Resources section
    expect(fullText.indexOf('[44]')).toBeLessThan(fullText.indexOf('Resources'));
    expect(fullText.indexOf('Resources')).toBeLessThan(fullText.indexOf('Organizing team'));
  });

  it('math151_p12: does not merge section header with body into run-on', () => {
    const { entries, width, height } = loadPage('math151_p12');
    const filtered = filterNonBodyItems(entries, width, height);
    const sorted = filtered; // stream order

    // Check that "How to count" appears as distinct text, not merged with surrounding
    const howToCount = sorted.find((e) => e.item.str.includes('How to count'));
    expect(howToCount).toBeDefined();
  });
});
